"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.testClock = exports.listClock = exports.blockClock = exports.deleteClock = exports.createClock = exports.removeClock = exports.writeClock = exports.readClock = exports.updateClock = exports.initClock = void 0;
var clock_buzz_1 = require("./buz/clock.buzz");
Object.defineProperty(exports, "initClock", { enumerable: true, get: function () { return clock_buzz_1.initClock; } });
var clock_buzz_2 = require("./buz/clock.buzz");
Object.defineProperty(exports, "updateClock", { enumerable: true, get: function () { return clock_buzz_2.updateClock; } });
var clock_buzz_3 = require("./buz/clock.buzz");
Object.defineProperty(exports, "readClock", { enumerable: true, get: function () { return clock_buzz_3.readClock; } });
var clock_buzz_4 = require("./buz/clock.buzz");
Object.defineProperty(exports, "writeClock", { enumerable: true, get: function () { return clock_buzz_4.writeClock; } });
var clock_buzz_5 = require("./buz/clock.buzz");
Object.defineProperty(exports, "removeClock", { enumerable: true, get: function () { return clock_buzz_5.removeClock; } });
var clock_buzz_6 = require("./buz/clock.buzz");
Object.defineProperty(exports, "createClock", { enumerable: true, get: function () { return clock_buzz_6.createClock; } });
var clock_buzz_7 = require("./buz/clock.buzz");
Object.defineProperty(exports, "deleteClock", { enumerable: true, get: function () { return clock_buzz_7.deleteClock; } });
var clock_buzz_8 = require("./buz/clock.buzz");
Object.defineProperty(exports, "blockClock", { enumerable: true, get: function () { return clock_buzz_8.blockClock; } });
var clock_buzz_9 = require("./buz/clock.buzz");
Object.defineProperty(exports, "listClock", { enumerable: true, get: function () { return clock_buzz_9.listClock; } });
var clock_buzz_10 = require("./buz/clock.buzz");
Object.defineProperty(exports, "testClock", { enumerable: true, get: function () { return clock_buzz_10.testClock; } });
//# sourceMappingURL=clock.buzzer.js.map