"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createEmotion = exports.deleteEmotion = exports.removeEmotion = exports.writeEmotion = exports.readEmotion = exports.selectEmotion = exports.updateEmotion = exports.initEmotion = void 0;
var emotion_buzz_1 = require("./buz/emotion.buzz");
Object.defineProperty(exports, "initEmotion", { enumerable: true, get: function () { return emotion_buzz_1.initEmotion; } });
var emotion_buzz_2 = require("./buz/emotion.buzz");
Object.defineProperty(exports, "updateEmotion", { enumerable: true, get: function () { return emotion_buzz_2.updateEmotion; } });
var emotion_buzz_3 = require("./buz/emotion.buzz");
Object.defineProperty(exports, "selectEmotion", { enumerable: true, get: function () { return emotion_buzz_3.selectEmotion; } });
var emotion_buzz_4 = require("./buz/emotion.buzz");
Object.defineProperty(exports, "readEmotion", { enumerable: true, get: function () { return emotion_buzz_4.readEmotion; } });
var emotion_buzz_5 = require("./buz/emotion.buzz");
Object.defineProperty(exports, "writeEmotion", { enumerable: true, get: function () { return emotion_buzz_5.writeEmotion; } });
var emotion_buzz_6 = require("./buz/emotion.buzz");
Object.defineProperty(exports, "removeEmotion", { enumerable: true, get: function () { return emotion_buzz_6.removeEmotion; } });
var emotion_buzz_7 = require("./buz/emotion.buzz");
Object.defineProperty(exports, "deleteEmotion", { enumerable: true, get: function () { return emotion_buzz_7.deleteEmotion; } });
var emotion_buzz_8 = require("./buz/emotion.buzz");
Object.defineProperty(exports, "createEmotion", { enumerable: true, get: function () { return emotion_buzz_8.createEmotion; } });
//# sourceMappingURL=emotion.buzzer.js.map