"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TYPE_DISK = exports.COLOR_DISK = exports.SWATCH_DISK = exports.EXIST_DISK = exports.DELETE_DISK = exports.ENSURE_DISK = exports.TRASH_DISK = exports.BATCH_DISK = exports.FRAME_DISK = exports.COPY_DISK = exports.LOAD_LIST_DISK = exports.INDEX_DISK = exports.WRITE_DISK = exports.READ_DISK = exports.UPDATE_DISK = exports.INIT_DISK = void 0;
exports.INIT_DISK = '[Disk action] Init Disk';
exports.UPDATE_DISK = '[Disk action] Update Disk';
exports.READ_DISK = '[Disk action] Read Disk';
exports.WRITE_DISK = '[Disk action] Write Disk';
exports.INDEX_DISK = '[Index action] Index Disk';
exports.LOAD_LIST_DISK = '[Load_list action] Load_list Disk';
exports.COPY_DISK = '[Copy action] Copy Disk';
exports.FRAME_DISK = '[Frame action] Frame Disk';
exports.BATCH_DISK = '[Batch action] Batch Disk';
exports.TRASH_DISK = '[Trash action] Trash Disk';
exports.ENSURE_DISK = '[Ensure action] Ensure Disk';
exports.DELETE_DISK = '[Delete action] Delete Disk';
exports.EXIST_DISK = "[Exist action] Exist Disk";
exports.SWATCH_DISK = "[Swatch action] Swatch Disk";
exports.COLOR_DISK = "[Color action] Color Disk";
exports.TYPE_DISK = "[Type action] Type Disk";
//# sourceMappingURL=disk.action.js.map